### ISSUE TITLE
Failure: No such entity

### ISSUE THREAD

**Issue by vsjoqvist** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#10]
i get an error when i try to move  an application into the sink

**Comment by edisionnano** [comment]
Theres a chance the applicationn you are trying to move has changed id

**Comment by edisionnano** [comment]
Ill close your issue for now. Applications sometimes reconnect and thus change id. Contact me on Discord for further help, my Username#Discriminator is at the bottom of the tutorial.
