### ISSUE TITLE
Pop OS - downloaded chrome - doesn't seem to work

### ISSUE THREAD

**Issue by denierlexiese** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#11]
Tried with pop os 21.10 - downloaded chrome, and put extension in browser.

With extension activated, I can't press the share screen button in the bottom left hand corner in discord in the webapp.  The buttons there, but nothing happens.  When I deactivate the extension, share button works as normal.

**Comment by edisionnano** [comment]
Press ctrl+shift+I to open Chromium's dev settings and go to the console, there you can see what fails

**Comment by edisionnano** [comment]
The user got it working
