### ISSUE TITLE
Virtmic source code?

### ISSUE THREAD

**Issue by luluco250** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#13]
Hey, I'd first like to thank you for this, it works flawlessly and it's great to be able to share audio with friends without resorting to a Windows VM.

I'm just curious about the `virtmic` tool, is there a reason why it's distributed as a binary? Could it be open sourced?

I'm willing to help if possible.

**Comment by edisionnano** [comment]
If you read the tips and notes section you'll see that it's actualy open source

**Comment by luluco250** [comment]
Oh, my bad! Thanks for letting me know.
