### ISSUE TITLE
virtmic tool fails to execute on Steam Deck

### ISSUE THREAD

**Issue by Ginjutsu** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#16]
When attempting to run the provided virtmic tool on an "unrooted" Steam Deck, Konsole spits out the following error:

`./virtmic: /usr/lib/libc.so.6: version 'GLIBC_2.34' not found (required by ./virtmic)`

If there was a way to work around this issue without resorting to disabling read-only for root on the Deck, it would be greatly appreciated by myself and others :)

**Comment by D3SOX** [comment]
Use the [virtmic_steamdeck](https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux/blob/main/virtmic_steamdeck) binary
