### ISSUE TITLE
Make work with actual Discord

### ISSUE THREAD

**Issue by Melechtna** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#17]
If you could make the addon work with BetterDiscord, it might be able to be made to work with actual Discord rather than needing to use the browser

**Comment by edisionnano** [comment]
Read the readme, it isn't as simple as that. Discord's client doesn't use javascript methods to perform screen capture but a native node binary instead. The method used in this repo is irrelevant to the client. Someone would need to reverse engineer and reimplement discord_voice.node

**Comment by edisionnano** [comment]
> https://github.com/mwittrien/BetterDiscordAddons/tree/master/Library/
> 
> This is a plugin designed for BetterDiscord, please note the extension of said plugin, as BetterDiscord, does.

How does this help
