### ISSUE TITLE
Get it Implemented into Webcord

### ISSUE THREAD

**Issue by snoweuph** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#19]
There is a nice Discord Client called [Webcord](https://github.com/SpacingBat3/WebCord) that is its own electron app that uses the web version and works API less, so its not against TOS. It would be pretty cool to implement this into that project. out of my sight the only 2 down sights that client currently has are
1. No screen share sound
2. no Discord RPC

its using the newest version of the chromium framework and because it is a real app, you've got more access, meaning that you can spawn the virtmic by yourself in the background and get the name of what to share directly

I would love to see this working

**Comment by edisionnano** [comment]
There's already an issue open there, https://github.com/SpacingBat3/WebCord/issues/154

**Comment by snoweuph** [comment]
![grafik](https://user-images.githubusercontent.com/76737863/178153109-395348e2-8efe-4d57-aa0d-6bfbceabbe43.png)
