### ISSUE TITLE
Suggest ViolentMonkey or GreaseMonkey instead of Tampermonkey

### ISSUE THREAD

**Issue by indeedwatson** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#2]
Just a suggestion, Tampermonkey is not open source, unlike the other two. Feel free to close this whether you like the suggestion or not.

**Comment by indeedwatson** [comment]
Greasemonkey is ff only, I tried violentmonkey on chromium with no issues.

**Comment by D3SOX** [comment]
Thank you for pointing out that it's not open source. I also switched to Violentmonkey on Firefox
