### ISSUE TITLE
Allow specifying app with argument

### ISSUE THREAD

**Issue by Radiicall** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#20]
Can you add a way to specify app using an argument?
for example i want to have a script that just does
`$ virtmic --app alsa_output.usb-Razer_Razer_Nari_Ultimate-00.analog-game`
instead of having to do this manually
```
$ virtmic                                                                   
Enter an application you'd like to link to the virtual microphone: alsa_output.usb-Razer_Razer_Nari_Ultimate-00.analog-game
```

**Comment by maltejur** [comment]
> i want to have a script

Just do

```bash
echo "alsa_output.usb-Razer_Razer_Nari_Ultimate-00.analog-game" | ./virtmic
```

then, that should work.

**Comment by Radiicall** [comment]
Also it would be nice if you actually put source code in the repo and used releases because some people are weary of running code they cant read
