### ISSUE TITLE
Pulse loopback capture on the horizon

### ISSUE THREAD

**Issue by rhoot** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#27]
I was (once again) looking at the links in the README, and after a bit of browsing encountered this Chromium feature request labeled [[Linux] System loopback audio capture](https://bugs.chromium.org/p/chromium/issues/detail?id=1143761). Filed in 2020, it looks like it was just closed as completed in Dec, 2023.

According to Chromium Dash [that commit is currently in the beta channel](https://chromiumdash.appspot.com/commit/9a3d5ea818e66821c8a87b11b842dfd47c023608). And looking at electron's current `main` branch they're currently on 122.0.6194.0. So it's not quite there yet, but once electron updates it could be worth investigating if this can all just be solved by just setting that flag.

**Comment by edisionnano** [comment]
Interesting, will keep an eye on it. Thx

**Comment by edisionnano** [comment]
This can now be closed
