### ISSUE TITLE
Being able to hear application audio

### ISSUE THREAD

**Issue by tam-carre** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#4]
Hi,

`pactl load-module module-null-sink sink_name=vspeaker sink_properties=device.description=virtual_speaker`

I've managed to screenshare with audio by creating a sink with the above command and redirecting application playback to that sink, while setting the sink as the screenshare recording source. However, I can only hear the application audio myself when focusing on my browser window. Can you recommend a way I can listen to the audio even when not focusing on the browser window?

**Comment by edisionnano** [comment]
Follow the way I describe (let it capture the default device) and then use qjackctl to connect the audio of the app you want instead of making a virtual output.

**Comment by tam-carre** [comment]
Haven't had time to revisit this, but thanks for getting back to me.
