### ISSUE TITLE
JACK audio server support

### ISSUE THREAD

**Issue by kotarou3** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#7]
Based on the userscript in the guide, I made some minor modifications to get it working with the JACK audio server talking to PulseAudio.

Specifically, I wanted the audio sent to the screenshare stream to come directly from a JACK source, and I was able to do this.

The steps are as follows:
 1. Have an existing PulseAudio-to-JACK bridge set-up and working (outside the scope of this quick guide)
 2. Run `pactl load-module module-jack-source client_name=Stream connect=no channels=2`
 3. Wire up the newly added "Stream" sink in your JACK patchbay of choice
 4. Run the below userscript in Chromium with Discord open
 5. Stream as per normal, but now audio will come directly from the "Stream" JACK sink

You can pick a different name for the JACK sink, but be sure to change all occurrences of "Stream" in the `pactl` command and the userscript below to match

```js
navigator.mediaDevices.chromiumGetDisplayMedia = navigator.mediaDevices.getDisplayMedia;
navigator.mediaDevices.getDisplayMedia = async () => {
    const gdm = await navigator.mediaDevices.chromiumGetDisplayMedia({
        video: true,
        audio: true
    });
    
    const devices = await navigator.mediaDevices.enumerateDevices();
    let deviceId = null;
    for (const device of devices)
        if (device.label === "JACK source (Stream)")
            deviceId = device.deviceId;
            
    if (deviceId) {
        let captureSystemAudioStream = await navigator.mediaDevices.getUserMedia({
            audio: {
                deviceId: { exact: deviceId },
                autoGainControl: false,
                echoCancellation: false,
                noiseSuppression: false
            }
        });
        let [track] = captureSystemAudioStream.getAudioTracks();
        gdm.addTrack(track);
    } else {
        console.log("Couldn't find desired device");
        console.log(devices);
    }
    return gdm;
};
```

---

I'm not sure how to incorporate this into the master guide, so I didn't make this as a pull request. It's quite a niche-of-a-niche problem to have anyways.

But I just wanted to share in case anyone else has the same problem

**Comment by edisionnano** [comment]
Cant you rename the stream to virtmic or use it as a source when creating a virtual microphone called virtmic? That way you shouldn't have to edit the userscript.

**Comment by kotarou3** [comment]
Probably yes, but I didn't want to mess with pulseaudio-internal audio routing so just modifying the script was the simplest way for me

**Comment by edisionnano** [comment]
> Probably yes, but I didn't want to mess with pulseaudio-internal audio routing so just modifying the script was the simplest way for me

You could set client_name to virtmic then and instead of == check for a substring (contains virtmic)

**Comment by edisionnano** [comment]
I've merged the two scripts, if you ever need to use jack as you did in your way you can always create virtmic and use JACK source (Stream) as the master. I'm closing the issue for now, feel free to reopen if you feel I need to document this further.
