### ISSUE TITLE
captured audio plays back when discord is focused

### ISSUE THREAD

**Issue by matko** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#8]
The workaround described in this readme works great for me. I'm using a combine-sink to route my game audio to my headset as well as a sink whose monitor I use for capturing in discord. So both me and other people can hear my game audio while I am in-game. So far so good.

However, when I go into the discord window itself while streaming, my captured game audio plays back, very slightly out of sync with the game audio I'm already hearing, which is pretty annoying. It looks like the video element that discord displays now also has the audio stream. As a workaround, I can right-click the video element, select 'Show all controls', and then mute the stream. However, various actions within discord will refresh this element causing it to unmute again.

I suspect there's some way to stop this from happening. After all, if I can manually mute that displayed stream, a script can probably do so as well. Unfortunately I don't know enough about discord, chromium and browser javascript to make it happen.

Any ideas?

**Comment by edisionnano** [comment]
That issue appeared some months ago. It's a regression from Discord's side. Discord doesn't let you disable your stream's preview either.  This doesn't happen because of the script, if you screenshare a Chrome tab with audio it will still happen. I tried to reach Discord support via mail but they were answering me as if I was asking support for the client instead then closed my issue. If anyone wants to try contacting them again be my guest.

**Comment by matko** [comment]
You're right. I just tried sharing a chromium tab without the script enabled and it does the exact same thing. It's not linux specific either, as the same thing happens in chromium/chrome on windows. I'll see if I can reach out to support but I don't have high hopes.

Incidentally, I found out that Discord does let you disable your stream's preview, at least temporarily. When you're in the voice channel (looking at the video participants tile/focus screen), you can right click your stream preview and deselect 'Show My Screen Share'. This disables it for the rest of the stream. This seems like it is a better solution than my initial workaround through 'Show all controls' on the video element, as it persists while navigating around in discord itself. Only disadvantage is that the video preview is lost, but I guess that's just another thing to live with if I want to stream video with audio through discord on linux.

Thanks for your help.

**Comment by edisionnano** [comment]
Does this still occur?

**Comment by edisionnano** [comment]
After testing, this appears to have been fixed. Will reopen if some has had an experience that's different than mine.
